domain_controller:
  host: 10.20.0.8
  host_history:
  - 10.20.0.8
  - 10.20.0.13
  - 10.20.8.50
  - 10.20.0.4
  port: 22
  user: nvidia
  password: nvidia
  key_filename: ''
  host_work_dir: /home/nvidia/work/anyverse
  container_name: agent_dev_nvidia
  container_work_dir: /anyverse
  container_user: admin
pc:
  ip: 10.20.0.3
  user: wujie
  password: '123456'
  cyclonedds_path: ''
ros:
  domain_id: 40
  localhost_only: 0
  rmw: rmw_cyclonedds_cpp
  cyclonedds_uri: /anyverse/config/cyclonedds.xml
  network_interface: eth5
git:
  branch: dev/pnc
  repo: git@gitlab.anyverse.work:dev/anyverse.git
  host_clone_parent: /home/nvidia/work
docker:
  daemon_json_path: /etc/docker/daemon.json
  registry_mirrors:
  - https://docker.xuanyuan.me
  - https://docker.1ms.run
  - https://hub.rat.dev
  - https://registry.docker-cn.com
  insecure_registries:
  - docker.anyverse.work
  - registry.docker-cn.com
moveit:
  moveit_config_package: kitt_1_5_robot_with_zx90d_moveit
  controller_package: hardware_integration
  controller_launch: controller.launch.py
  latency_script: controller_state_latency6.py
  hw_params_relpath: src/pnc/config/moveit_config/kitt_1_5_robot_with_zx90d_moveit/config/kitt_1_5_robot_with_zx90d_hw_params.yaml
report:
  output_dir: reports
